version: '3.8'

services:
  riskdoc-app:
    build:
      context: .  # 명령어 실행 위치를 프로젝트 루트로 지정
      dockerfile: docker/Dockerfile # 레시피 파일 위치 지정
    container_name: riskdoc_container
    ports:
      - "8501:8501" # 내 컴퓨터 8501 포트 -> 도커 안의 8501 포트 연결
    env_file:
      - .env # Gemini API 키를 도커 안으로 안전하게 넘겨줌
    restart: unless-stopped 